version: '3'
services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: changeme.
      MYSQL_DATABASE: mcaz_pv_prod
      MYSQL_USER: changeme
      MYSQL_PASSWORD: changeme.
      UPLOAD_LIMIT: 10000000000
    ports:
      - "9907:3306"
    networks:
      - mydb
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql 
      - ~/epv-mysql-data:/var/lib/mysql
  web:
    build: .
    container_name: epv_web
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - "8766:80"
    networks:
      - mydb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pv_admin
    ports:
      - 8184:80
    environment:
      MYSQL_USER: changeme
      MYSQL_PASSWORD: changeme.
      MYSQL_ROOT_PASSWORD: changeme.
      UPLOAD_LIMIT: 10000000000
    networks:
      - mydb
    # volumes:
    #   - ./database.sql:/docker-entrypoint-initdb.d/database.sql 

networks:
  mydb:
