<?php
// in config/e2b_map.php
return ['faute' => [
    'ichicsr' => '&nbsp;',
    'ichicsrmessageheader' => '&nbsp;',
    'safetyreport' => '&nbsp;',
    '0' => '&nbsp;',
    '1' => '&nbsp;',
    '2' => '&nbsp;',
    'messagetype' => '<b>Message Type</b>',
    'messageformatversion' => 'Version',
    'messageformatrelease' => 'Release',
    'messagenumb' => 'Number',
    'ichicsrmessageheader' => '&nbsp;',
    'messagetype' => 'Message Type',
    'messageformatversion' => 'Message Format',
    'messageformatrelease' => 'Message Format Release',
    'messagenumb' => 'Message Number',
    'messagesenderidentifier' => 'Message Sender Identifier',
    'messagereceiveridentifier' => 'Message Receiver',
    'messagedateformat' => 'Message Date Format',
    'messagedate' => 'Message Date',
    'safetyreportversion' => 'Safety Report Version',
    'safetyreport' => '&nbsp;',
    'safetyreportid' => 'Sender\'s (Case) Safety Report Unique Identifier',
    'primarysourcecountry' => 'Country of the primary',
    'occurcountry' => 'Country where the reaction/event occurred',
    'transmissiondateformat' => 'Date of this transmission format',
    'transmissiondate' => 'Date of this transmission',
    'reporttype' => 'Type of report <small>(1=Spontaneous, 2=Report from study, 3=Other, 4=Not available to sender)</small>',
    'serious' => 'Serious <small>(1=Yes 2=No)</small>',
    'seriousnessdeath' => 'Results in death <small>(1=Yes 2=No)</small>',
    'seriousnesslifethreatening' => 'Life threatening <small>(1=Yes 2=No)</small>',
    'seriousnesshospitalization' => 'Caused/prolonged hospitalization <small>(1=Yes 2=No)</small>',
    'seriousnessdisabling' => 'Disabling/Incapacitating <small>(1=Yes 2=No)</small>',
    'seriousnesscongenitalanomali' => 'Congenital anomaly/birth defect <small>(1=Yes 2=No)</small>',
    'seriousnessother' => 'Other medically important condition <small>(1=Yes 2=No)</small>',
    'receivedateformat' => 'Date report was first received from source format',
    'receivedate' => 'Date report was first received from source',
    'receiptdateformat' => 'Date of receipt of the most recent information for this report',
    'receiptdate' => 'Date of receipt of the most recent information for this report',
    'additionaldocument' => 'Are additional documents available',
    'documentlist' => 'List of documents held by sender',
    'fulfillexpeditecriteria' => 'Does this case fulfill the local criteria for an expedited report?',
    'authoritynumb' => 'Regulatory authority\'s case report number',
    'companynumb' => 'Other sender\'s case report number',
    'duplicate' => 'Other case identifiers in previous transmissions',
    'duplicatesource' => 'Source(s) of the case identifier',
    'duplicatenumb' => 'Case identifiers',
    'linkreportnumb' => 'Identification number of the report which is',
]];
