<?php
// in config/e2b_map.php
$f = ['204' => 'CCYYMMDDHHMMSS', '102' => 'CCYYMMDD', '610' => 'CCYYMM', '602' => 'CCYY'];
$t = ['801' => 'Year',
'802' => 'Month',
'803' => 'Week',
'804' => 'Day',
'805' => 'Hour',
'806' => 'Minute',
'807' => 'Second'];
$y = ['1' => 'Yes', '2' => 'No'];
$q = ['1' => 'Physician',
'2' => 'Pharmacist',
'3' => 'Other Health Professional',
'4' => 'Lawyer',
'5' => 'Consumer or other non-health professional'];

return ['faute' => [
    'ichicsr' => ['label' => '&nbsp;&nbsp;&nbsp;&nbsp;', 'help' => ''],
    'ichicsrmessageheader' => ['label' => '&nbsp;&nbsp;&nbsp;&nbsp;', 'help' => ''],
    'safetyreport' => ['label' => '&nbsp;&nbsp;&nbsp;&nbsp;', 'help' => ''],
    '0' => ['label' => '&nbsp;&nbsp;&nbsp;&nbsp;', 'help' => ''],
    '1' => ['label' => '&nbsp;&nbsp;&nbsp;&nbsp;', 'help' => ''],
    '2' => ['label' => '&nbsp;&nbsp;&nbsp;&nbsp;', 'help' => ''],
    '3' => ['label' => '&nbsp;&nbsp;&nbsp;&nbsp;', 'help' => ''],
    '4' => ['label' => '&nbsp;&nbsp;&nbsp;&nbsp;', 'help' => ''],
    '5' => ['label' => '&nbsp;&nbsp;', 'help' => ''],
    '6' => ['label' => '&nbsp;&nbsp;', 'help' => ''],
    '7' => ['label' => '&nbsp;&nbsp;', 'help' => ''],
    '8' => ['label' => '&nbsp;&nbsp;', 'help' => ''],
    '9' => ['label' => '&nbsp;&nbsp;', 'help' => ''],
    'reportduplicate' => ['label' => '&nbsp;&nbsp;&nbsp;&nbsp;', 'help' => ''],
    'primarysource' => ['label' => '&nbsp;&nbsp;&nbsp;&nbsp;', 'help' => ''],
    'sender' => ['label' => '&nbsp;&nbsp;&nbsp;&nbsp;', 'help' => ''],
    'patient' => ['label' => '&nbsp;&nbsp;&nbsp;&nbsp;', 'help' => ''],
    'reaction' => ['label' => '&nbsp;&nbsp;&nbsp;&nbsp;', 'help' => ''],
    'drug' => ['label' => '&nbsp;&nbsp;&nbsp;&nbsp;', 'help' => ''],
    'activesubstance' => ['label' => '&nbsp;&nbsp;&nbsp;&nbsp;', 'help' => ''],
    'drugreactionrelatedness' => ['label' => '&nbsp;&nbsp;&nbsp;&nbsp;', 'help' => ''],
    'summary' => ['label' => '&nbsp;&nbsp;&nbsp;&nbsp;', 'help' => ''],
    'messageformatversion' => ['label' => 'Version', 'help' => ''],
    'messageformatrelease' => ['label' => 'Release', 'help' => ''],
    'messagenumb' => ['label' => 'Number', 'help' => ''],
    'ichicsrmessageheader' => ['label' => '&nbsp;&nbsp;&nbsp;&nbsp;', 'help' => ''],
    'messagetype' => ['label' => 'Message Type', 'help' => ''],
    'messageformatversion' => ['label' => 'Message Format', 'help' => ''],
    'messageformatrelease' => ['label' => 'Message Format Release', 'help' => ''],
    'messagenumb' => ['label' => 'Message Number', 'help' => ''],
    'messagesenderidentifier' => ['label' => 'Message Sender Identifier', 'help' => ''],
    'messagereceiveridentifier' => ['label' => 'Message Receiver', 'help' => ''],
    'messagedateformat' => ['label' => 'Message Date Format', 'help' => ''],
    'messagedate' => ['label' => 'Message Date', 'help' => ''],
    'safetyreportversion' => ['label' => 'Safety Report Version', 'help' => ''],
    'safetyreport' => ['label' => '&nbsp;&nbsp;&nbsp;&nbsp;', 'help' => ''],
    'safetyreportid' => ['label' => 'Sender\'s Identifier', 'help' => ''],
    'primarysourcecountry' => ['label' => 'Country of the primary', 'help' => ''],
    'occurcountry' => ['label' => 'Country where the reaction/event occurred', 'help' => ''],
    'transmissiondateformat' => ['label' => 'Date of this transmission format', 'help' => $f],
    'transmissiondate' => ['label' => 'Date of this transmission', 'help' => ''],
    'reporttype' => ['label' => 'Type of report', 'help' => ['1' => 'Spontaneous', '2' => 'Report from study', '3' => 'Other', '4' => 'Not available to sender']],
    'serious' => ['label' => 'Serious', 'help' => $y],
    'seriousnessdeath' => ['label' => 'Results in death', 'help' => $y],
    'seriousnesslifethreatening' => ['label' => 'Life threatening', 'help' => $y],
    'seriousnesshospitalization' => ['label' => 'Caused/prolonged hospitalization', 'help' => $y],
    'seriousnessdisabling' => ['label' => 'Disabling/Incapacitating', 'help' => $y],
    'seriousnesscongenitalanomali' => ['label' => 'Congenital anomaly/birth defect', 'help' => $y],
    'seriousnessother' => ['label' => 'Other medically important condition', 'help' => $y],
    'receivedateformat' => ['label' => 'Date report was first received from source format', 'help' => $f],
    'receivedate' => ['label' => 'Date report was first received from source', 'help' => ''],
    'receiptdateformat' => ['label' => 'Date of receipt format', 'help' => $f],
    'receiptdate' => ['label' => 'Date of receipt of the most recent information for this report', 'help' => ''],
    'additionaldocument' => ['label' => 'Are additional documents available', 'help' => $y],
    'documentlist' => ['label' => 'List of documents held by sender', 'help' => ''],
    'fulfillexpeditecriteria' => ['label' => 'Does this case fulfill the local criteria for an expedited report?', 'help' => $y],
    'authoritynumb' => ['label' => 'Regulatory authority\'s case report number', 'help' => ''],
    'companynumb' => ['label' => 'Other sender\'s case report number', 'help' => ''],
    'duplicate' => ['label' => 'Other case identifiers in previous transmissions', 'help' => $y],
    'duplicatesource' => ['label' => 'Source(s) of the case identifier', 'help' => ''],
    'duplicatenumb' => ['label' => 'Case identifiers', 'help' => ''],
    'linkreportnumb' => ['label' => 'Identification number of the report which is', 'help' => ''],
    'reportercountry' => ['label' => 'Reporter country code', 'help' => ''],
    'casenullification' => ['label' => 'Report nullification', 'help' => '1=Yes'],
    'nullificationreason' => ['label' => 'Reason for nullification', 'help' => ''],
    'qualification' => ['label' => 'Qualification', 'help' => $q],
    'sendertype' => ['label' => 'Type', 'help' => ['1' => 'Pharmaceutical Company', 
            '2' => 'Regulatory Authority', 
            '3' => 'Health professional', '4' => 'Regional Pharmacovigilance Center', 
            '5' => 'WHO Collaborating Center for International Drug Monitoring', '6' => 'Other']],
    'senderorganization' => ['label' => 'Sender organization', 'help' => ''],
    'senderdepartment' => ['label' => 'Sender department', 'help' => ''],
    'sendertitle' => ['label' => 'Sender title', 'help' => ''],
    'sendergivename' => ['label' => 'Sender given name', 'help' => ''],
    'sendermiddlename' => ['label' => 'Sender middle name', 'help' => ''],
    'senderfamilyname' => ['label' => 'Sender family name', 'help' => ''],
    'senderstreetaddress' => ['label' => 'Sender street address', 'help' => ''],
    'sendercity' => ['label' => 'Sender city', 'help' => ''],
    'senderstate' => ['label' => 'Sender state', 'help' => ''],
    'sendertelextension' => ['label' => 'Telephone extension', 'help' => ''],
    'senderpostcode' => ['label' => 'Sender post code', 'help' => ''],
    'sendercountrycode' => ['label' => 'Sender country code', 'help' => ''],
    'sendertel' => ['label' => 'Sender telephone', 'help' => ''],
    'patientinitial' => ['label' => 'Patient initials', 'help' => ''],
    'patientgpmedicalrecordnumb' => ['label' => 'GP medical record number', 'help' => ''],
    'patientspecialistrecordnumb' => ['label' => 'Specialist record number', 'help' => ''],
    'patienthospitalrecordnumb' => ['label' => 'Hospital record number', 'help' => ''],
    'patientinvestigationnumb' => ['label' => 'Investigation number', 'help' => ''],
    'primarysourcereaction' => ['label' => 'Reaction/event as reported by primary source', 'help' => ''],
    'reactionmeddraversionllt' => ['label' => 'MedDRA version for reaction/event term LLT', 'help' => ''],
    'reactionmeddrallt' => ['label' => 'Reaction/event in MedDRA terminology (LLT)', 'help' => ''],
    'reactionmeddraversionpt' => ['label' => 'MedDRA version for reaction/event term PT', 'help' => ''],
    'reactionmeddrapt' => ['label' => 'Reaction/event MedDRA term (PT)', 'help' => ''],
    'termhighlighted' => ['label' => 'Term highlighted by the reporter', 'help' => ['1' => 'Yes, highlighted by the reporter, NOT serious', '2' => 'No, not highlighted by the reporter, NOT serious', '3' => 'Yes, highlighted by the reporter, SERIOUS', '4' => 'No, not highlighted by the reporter, SERIOUS']],
    'reactionstartdateformat' => ['label' => 'Date of start of reaction', 'help' => ['102' => 'Format CCYYMMDD',
'203' => 'Format CCYYMMDDHHMM',
'610' => 'Format CCYYMM',
'602' => 'Format CCYY']],
    'reactionenddateformat' => ['label' => 'Date of end of reaction/event', 'help' => '102 - Format
CCYYMMDD,
203 - Format
CCYYMMDDHHMM,
610 - Format CCYYMM,
602 - Format CCYY
'],
    'reactionenddate' => ['label' => 'Date of end of reaction/event', 'help' => ''],
    'reactionduration' => ['label' => 'Duration of reaction/event', 'help' => ''],
    'reactiondurationunit' => ['label' => 'Duration of reaction/event', 'help' => ['801' => 'Year',
'802' => 'Month',
'803' => 'Week',
'804' => 'Day',
'805' => 'Hour',
'806' => 'Minute',
'807' => 'Second']],
    'reactionfirsttime' => ['label' => 'Time interval unit between suspect drug administration and start of reaction/event', 'help' => ''],
    'reactionlasttime' => ['label' => 'Time interval between last dose and start of reaction/event', 'help' => ''],
    'reactionstartdate' => ['label' => 'Date of start of reaction/event', 'help' => ''],
    'reactionenddate' => ['label' => 'Date of end of reaction/event', 'help' => ''],
    'drugcharacterization' => ['label' => 'Characterization of drug role', 'help' => '1=Suspect,
2=Concomitant,
3=Interacting
'],
    'reactionmeddrapt' => ['label' => 'Reaction/event MedDRA term (PT)', 'help' => ''],
    'medicinalproduct' => ['label' => 'Proprietary medicinal product name', 'help' => ''],
    'activesubstancename' => ['label' => 'Active Drug substance names', 'help' => ''],
    'obtaindrugcountry' => ['label' => 'Country where the drug was obtained', 'help' => ''],
    'drugbatchnumb' => ['label' => 'Batch/lot number', 'help' => ''],
    'drugauthorizationnumb' => ['label' => 'Authorization/Application Number', 'help' => ''],
    'drugauthorizationcountry' => ['label' => 'Country of authorization/application', 'help' => ''],
    'drugauthorizationholder' => ['label' => 'Name of holder/applicant', 'help' => ''],
    'drugstructuredosagenumb' => ['label' => 'dose (number)', 'help' => ''],
    'drugstructuredosageunit' => ['label' => 'dose (unit)', 'help' => ['001' => 'kg kilogram(s)',
'002' => 'G gram(s)',
'003' => 'Mg milligram(s)',
'004' => 'g microgram(s)',
'005' => 'ng nanogram(s)',
'006' => 'pg picogram(s)',
'007' => 'mg/kg',
'milligram(s)/kilogram',
'008' => 'g/kg',
'microgram(s)/kilogram',
'009' => 'mg/m 2',
'milligram(s)/sq. meter',
'010' => 'g/ m 2',
'microgram(s)/ sq. Meter',
'011' => 'l litre(s)',
'012' => 'ml millilitre(s)',
'013' => 'l microlitre(s)',
'014' => 'Bq becquerel(s)',
'015' => 'GBq',
'gigabecquerel(s)',
'016' => 'MBq',
'megabecquerel(s)',
'017' => 'Kbq',
'kilobecquerel(s)',
'018' => 'Ci curie(s)',
'019' => 'MCi millicurie(s)',
'020' => 'Ci microcurie(s)',
'021' => 'NCi nanocurie(s)',
'022' => 'Mol mole(s)',
'023' => 'Mmol millimole(s)',
'024' => 'mol micromole(s)',
'025' => 'Iu international unit(s)',
'026' => 'Kiu iu(1000s)',
'027' => 'Miu iu(1,000,000s)',
'028' => 'iu/kg iu/kilogram',
'029' => 'Meq milliequivalent(s)',
'030' => '% percent',
'031' => 'Gtt drop(s)',
'032' => 'DF dosage form']],
    'drugseparatedosagenumb' => ['label' => 'number of separate dosages', 'help' => ''],
    'drugintervaldosageunitnumb' => ['label' => 'number of units in the interval', 'help' => ''],
    'drugintervaldosagedefinition' => ['label' => 'definition of the interval', 'help' => '801=Year,
802=Month,
803=Week,
804=Day,
805=Hour,
806=Minute
'],
    'drugcumulativedosagenumb' => ['label' => 'cumulative dose to first reaction (number)', 'help' => ''],
    'drugcumulativedosageunit' => ['label' => 'cumulative dose to first reaction (unit)', 'help' => ''],
    'drugdosagetext' => ['label' => 'Dosage text', 'help' => ''],
    'drugdosageform' => ['label' => 'Pharmaceutical form (Dosage form)', 'help' => ''],
    'drugadministrationroute' => ['label' => 'Route of administration', 'help' => ['001' => 'Auricular (otic)',
'002' => 'Buccal',
'003' => 'Cutaneous',
'004' => 'Dental',
'005' => 'Endocervical',
'006' => 'Endosinusial',
'007' => 'Endotracheal',
'008' => 'Epidural',
'009' => 'Extra-amniotic',
'010' => 'Hemodialysis',
'011' => 'Intra corpus cavernosum',
'012' => 'Intra-amniotic',
'013' => 'Intra-arterial',
'014' => 'Intra-articular',
'015' => 'Intra-uterine',
'016' => 'Intracardiac',
'017' => 'Intracavernous',
'018' => 'Intracerebral',
'019' => 'Intracervical',
'020' => 'Intracisternal',
'021' => 'Intracorneal',
'022' => 'Intracoronary',
'023' => 'Intradermal',
'024' => 'Intradiscal (intraspinal)',
'025' => 'Intrahepatic',
'026' => 'Intralesional',
'027' => 'Intralymphatic',
'028' => 'Intramedullar (bone marrow)',
'029' => 'Intrameningeal',
'030' => 'Intramuscular',
'031' => 'Intraocular',
'032' => 'Intrapericardial',
'033' => 'Intraperitoneal',
'034' => 'Intrapleural',
'035' => 'Intrasynovial',
'036' => 'Intratumor',
'037' => 'Intrathecal',
'038' => 'Intrathoracic',
'039' => 'Intratracheal',
'040' => 'Intravenous bolus',
'041' => 'Intravenous drip',
'042' => 'Intravenous (not otherwise specified)',
'043' => 'Intravesical',
'044' => 'Iontophoresis',
'045' => 'Nasal',
'046' => 'Occlusive dressing technique',
'047' => 'Ophthalmic',
'048' => 'Oral',
'049' => 'Oropharingeal',
'050' => 'Other',
'051' => 'Parenteral',
'052' => 'Periarticular',
'053' => 'Perineural',
'054' => 'Rectal',
'055' => 'Respiratory (inhalation)',
'056' => 'Retrobulbar',
'057' => 'Sunconjunctival',
'058' => 'Subcutaneous',
'059' => 'Subdermal',
'060' => 'Sublingual',
'061' => 'Topical',
'062' => 'Transdermal',
'063' => 'Transmammary',
'064' => 'Transplacental',
'065' => 'Unknown',
'066' => 'Urethral',
'067' => 'Vaginal']],
    'actiondrug' => ['label' => 'Action(s) taken with drug', 'help' => ['1' => 'Drug withdrawn',
            '2'=>'Dose reduced',
            '3'=>'Dose increased',
            '4'=>'Dose not changed',
            '5'=>'Unknown',
            '6'=>'Not applicable',
            ]],
    'drugindication' => ['label' => 'Indication for use in the case', 'help' => ''],
    'drugreactionasses' => ['label' => 'Reaction assessed', 'help' => ''],
    'drugassessmentmethod' => ['label' => 'Method of assessment', 'help' => ''],
    'drugreactionassesmeddraversion' => ['label' => 'MedDRA version for reaction assessed', 'help' => ''],
    'drugadditional' => ['label' => 'Additional information on drug', 'help' => ''],
    'narrativeincludeclinical' => ['label' => 'Case narrative including clinical course, therapeutic measures, outcome and additional relevant information.', 'help' => ''],
    'patientagegroup' => ['label' => 'Patient age group', 'help' => ['1' => 'Neonate',
'2' => 'Infant',
'3' => 'Child',
'4' => 'Adolescent',
'5' => 'Adult',
'6' => 'Elderly']],
    'patientsex' => ['label' => 'Sex', 'help' => ['1' => 'Male', '2' => 'Female']],
    'patientbirthdateformat' => ['label' => 'Date of birth format', 'help' => ['102' => 'CCYYMMDD']],
    'patientbirthdate' => ['label' => 'Date of birth', 'help' => ''],
    'patientonsetage' => ['label' => 'Age at time of onset of reaction/event', 'help' => ''],
    'patientonsetageunit' => ['label' => 'Age at time of onset of reaction/event', 'help' => [
        '800' => 'Decade',
        '801' => 'Year',
'802' => 'Month',
'803' => 'Week',
'804' => 'Day',
'805' => 'Hour',
'806' => 'Minute',
'807' => 'Second']],
]];
